[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "FTO"
version = "0.1.0"
requires-python = "==3.12.*"
dependencies = [
    "aegis-mas",
    "ollama>=0.6.1",
]

[tool.hatch.build.targets.wheel]
packages = ["src/fto"]

[tool.uv.sources]
aegis-mas = { git = "https://github.com/kfq20/AEGIS.git" }
