[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "FTO"
version = "0.1.0"
requires-python = "==3.12.*"
dependencies = [
    "aegis-mas",
    "litellm>=1.98.0",
    "llmlingua>=0.2.2",
    "llmmas-otel",
    "ollama>=0.6.1",
    "pytest>=9.1.1",
    "ruff>=0.15.12",
]

[tool.hatch.build.targets.wheel]
packages = ["src/fto"]

[tool.uv.sources]
aegis-mas = { git = "https://github.com/imoruz/AEGIS.git" }
llmmas-otel = { git = "https://github.com/vagabondboffin/llmmas-otel.git" }

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
]
